### ISSUE TITLE
CUADRO COMPARATIVO YADIRIA OLIVIA MIGUEL AGUILAR

### ISSUE THREAD

**Issue by yadiriaolivia** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-yadiriaolivia#1]
[cuadro comparativo Yadiria Olivia Miguel Aguilar.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-yadiriaolivia/files/9637732/cuadro.comparativo.Yadiria.Olivia.Miguel.Aguilar.pdf)

**Comment by 11042002** [comment]
Tu calificación es de: 18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
